### PR TITLE
Chinwe/bug fix

### PR DESCRIPTION
**Pull request by bianca-sparxs**
# Description
Design edits made on Schedule, Tracks and Workshops, and FAQ sections

# Reviewing

[Instructions on what parts of the code should be reviewed/tested.]

# Tests
I affirm that I've tested my code on:
- [x] Desktop
- [x] Tablet
- [x] Mobile
(Chrome tools counts)

### CODE REVIEW

**Review by lkwatson — CHANGES_REQUESTED** [review]
Please resolve conflicts with master.

Sponsor doc doesn't need to be added again. If there are changes, replace the current file.

**Comment by lkwatson** [comment]
Bump @bianca-sparxs

**Review by lkwatson — APPROVED** [review]

**Comment by lkwatson** [comment]
Looks good. @maridematte can you review and merge.

**Review by maridematte — APPROVED** [review]
Looks good!

**Pull request merged**
