### PR TITLE
Tracks and Workshops & Event Schedule

### PR DESCRIPTION
**Pull request by nampham148**
# Description
Change to use react-flexbox-grid instead of grid-styled for consistency
Make Tracks and Workshops look pretty. Add wavy background image
Add images (squares, grids, etc)

# Reviewing
How tracks and workshops look on mobile. Right now it looks not too bad but still not exactly as designed.

# Tests
I affirm that I've tested my code on:
- [x] Desktop
- [x] Tablet
- [x] Mobile
(Chrome tools counts)

### CODE REVIEW

**Review by maridematte — CHANGES_REQUESTED** [review]
The background images aren't quite aligned, and they cut on the lower border on some points.

**Comment by nampham148** [comment]
I made some changes. It's been pretty tough to make the wave provided collapse into the one shown in the mobile design. I kinda hack it by adding a second background img and make the top one collapse to the right and the bottom one collapse to the left (so that they can cover all the content). Can you check to see if it works?

**Comment by lkwatson** [comment]
What do you mean by collapse into one? I see two waves on the mobile design.

This is what I see:
screen shot 2018-07-31 at 5 39 53 pm

**Comment by nampham148** [comment]
I mean as screen width gets smaller the waves in desktop collapse into the waves shown in the mobile design.

I made some new commits to make sure the height and font-size grows when screen width grows past 1200px. The waves should be fully visible on big screens now.

**Comment by maridematte** [comment]
I feel like the new weight for the fonts on larger screens is a bit too much, it gets really big and looks a bit off from the rest of the website. But other than that and the waves everything looks good!

**Comment by nampham148** [comment]
I scaled the font size because as it was we would end up with too much empty space at the bottom of the waves. Maybe I'll try adding some margin in larger screens to address this

**Comment by maridematte** [comment]
Almost there! The flair of the schedule does not appear on mobile, and the flair from the tracks and workshops is too big on mobile.

**Comment by maridematte** [comment]
Flair from event schedule is still a bit off in mobile

**Review by maridematte — APPROVED** [review]

**Comment by maridematte** [comment]
Very nice, thank you for responding so quickly to the changes requested!

**Pull request merged**
