### PR TITLE
Create a new Contact Page to Work On

### PR DESCRIPTION
**Pull request by nampham148**
This PR just creates a new page at /contact_page. The component rendered for this page is at ContactPage.js

### CODE REVIEW

**Review by maridematte — CHANGES_REQUESTED** [review]
Can you add a submit button at the end of the forms? Also, make sure that the email field accepts only valid email formats!

**Comment by nampham148** [comment]
Let me add the email check. There's no button in the design so how should I style it?

**Comment by maridematte** [comment]
The same as the buttons on the attend and sponsor section of the main page. Just match the colors

**Comment by maridematte** [comment]
Nice! Almost everything is in order, its just missing the name and message to be a required field!

**Review by maridematte — APPROVED** [review]

**Review by lkwatson — APPROVED** [review]

**Comment by lkwatson** [comment]
Approving, asked @maridematte about font units, I see `px` which isn't great for responsiveness.

**Comment by maridematte** [comment]
I'm still gonna revise it today/tomorrow so I can put everything in order. Will change the units when I do that

**Pull request merged**
