### PR TITLE
fix spacing in hero text and tracks

### PR DESCRIPTION
**Pull request by nampham148**
Fix spacing on hero text and tracks. Switch "-" in event date to en dash.

# Reviewing

[Instructions on what parts of the code should be reviewed/tested.]

# Tests
I affirm that I've tested my code on:
- [x] Desktop
- [x] Tablet
- [x] Mobile
(Chrome tools counts)

### CODE REVIEW

**Review by maridematte — APPROVED** [review]

**Review by lkwatson — CHANGES_REQUESTED** [review]
Please remove `package-lock.json`. Otherwise looks good.

**Comment by nampham148** [comment]
What do you mean by remove package-lock.json? Like keep the file unchanged? The changes were auto generated.

**Comment by lkwatson** [comment]
Do `git rm --cache package-lock.json` so it's removed from git but stays local.

**Comment by nampham148** [comment]
image

I ran these commands and committed. My latest commit said there's no change to show though. Does this look good or did I do something wrong?

**Comment by lkwatson** [comment]
`git add .` adds all files, and undos the change you're trying to make. Use `git add -u`.

**Comment by nampham148** [comment]
Actually I realized that and in the last three commands I committed without using `git add .` I tried again using `git add -u` though, but it still says no changes to show.

**Comment by lkwatson** [comment]
Weird okay, I'll merge and try to resolve.

**Review by lkwatson — APPROVED** [review]

**Pull request merged**
