### PR TITLE
Add Navbar

### PR DESCRIPTION
**Pull request by ROODAY**
# Description

Added navbar to site, fixed some error output for FAQSection

# Reviewing

Click the links, resize the window, throw a T. Rex at it and hope it doesn't break

# Tests
I affirm that I've tested my code on:
- [x] Desktop
- [x] Tablet
- [x] Mobile (looks like poop for now)
(Chrome tools counts)

### CODE REVIEW

**Review by maridematte — APPROVED** [review]
Looks gud

**Review by lkwatson — CHANGES_REQUESTED** [review]
Can the underline for each tab be smaller to adhere to design more?

Also now that I'm looking at the design, doesn't quite make sense to have History distinguished the same as on-page elements. Can you loop back to design team and ask for a way to distinguish that this is going to click off?

**Comment by lkwatson** [comment]
Bump

**Comment by ROODAY** [comment]
@lkwatson Can you take a look/merge soon before more merge errors lol

**Comment by maridematte** [comment]
There is a misspelling in index.js in the FooterBar folder, the import should be "./footerbar". Also, the navbar is going over the scroll bar, please fix that.

**Comment by ROODAY** [comment]
@maridematte I changed the name to be Footerbar because it didn't make sense for just one file to not follow the naming convention

**Review by maridematte — CHANGES_REQUESTED** [review]
Mobile view is not right, it doesn't collapse and it only shows the logo and start of the menu

**Comment by lkwatson** [comment]
@ROODAY bump

**Comment by maridematte** [comment]
Rudy is not working on the Navbar anymore, for changes see Ken's branch

**Pull request closed without merging**
