### PR TITLE
First try at the site wide header text

### PR DESCRIPTION
**Pull request by mhendrick98**
Added a Header.js folder and file.
Updated App.js

https://trello.com/c/pnigp6BX/11-small-component-site-wide-header-text

### CODE REVIEW

**Review by warren — CHANGES_REQUESTED** [review]
Overall looks good, but I can't get `npm start` to compile since it looks like Prettier wants to make changes.

Could you try doing `prettier --write <filename>` to any files that prevent `npm start` from finishing, and then committing the new files?

Edit: if prettier isn't installed globally for you, do `npm install -g prettier` and that should let you use that command

**Comment by a--hoang** [comment]
@Warren-Partridge if u use yarn, yarn will execute scripts in node_modules without you having to install stuff globally

**Review by warren — APPROVED** [review]
LGTM

**Comment by lkwatson** [comment]
Can we see why checks aren't being run? Are they just not set up yet?

**Comment by a--hoang** [comment]
@lkwatson https://circleci.com/gh/Bostonhacks/beta/26 it's been skipped?

**Comment by mhendrick98** [comment]
@a--hoang @lkwatson In the config file for Travis, it's set so it'll only run when on the 'master' branch. My pr is coming from a branch that's not master. Not sure how you guys want to alter the script/workflow to accommodate this.


    working_directory: ~/beta

    branches:
      only:
        - master
    
    steps:
      - checkout

**Comment by lkwatson** [comment]
I can look into it later, but if you want to take it on compare it to how squadra does build checking.

**Comment by mhendrick98** [comment]
In the config file for Travis in Squadra, it doesn't have any specifications regarding branches. As far as I can tell, regardless of what the branch is the check will run. The only check regarding the branch that is done is if the branch is "master", it'll execute the squadra.rb script.

`      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bundle exec ruby squadra.rb
            fi`

I can file a new pr later tonight with a proposed change to the config file.

**Comment by lkwatson** [comment]
Nice, looks like CI is all good now.

@maridematte or @sarah256, can you provide your review and merge please.

**Review by maridematte — APPROVED** [review]
Looks good!

**Comment by lkwatson** [comment]
@mhendrick98 Are you able to merge? If so, hit the little arrow next to the merge button, and select "Squash and merge".

If not, it's a squadra issue to be fixed.

**Comment by mhendrick98** [comment]
@lkwatson It says I don't have write access to the repo.

**Comment by lkwatson** [comment]
Sigh github why you do this

**Pull request merged**
