### PR TITLE
Add MLH flag and code of conduct to site

### PR DESCRIPTION
**Pull request by sarah256**
# Description

Added MLH flag on desktop, and MLH code of conduct link.

# Reviewing

[Instructions on what parts of the code should be reviewed/tested.]

# Tests
I affirm that I've tested my code on:
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
(Chrome tools counts)

### CODE REVIEW

**Review by lkwatson — CHANGES_REQUESTED** [review]
Please add hyperlink to the CoC in the FAQ question "Are there any rules?" as well.

What's the proper strategy for the banner on mobile? I forget what we've done in the past / what others do.

Thank you :)

**Comment by sarah256** [comment]
@lkwatson added the hyperlink! 😊 IMO for mobile it's best to hide the banner, as I'm not quite sure how we would be able to display it without covering up a significant portion of the page.  Thoughts?

**Comment by maridematte** [comment]
I think we can take the banner off from the mobile if we have the mlh logo with our partners. Or we can make a special section for it?

**Comment by sarah256** [comment]
@maridematte I think that's a good idea :smiley:

**Pull request merged**
