### PR TITLE
Changed the text of registration section

### PR DESCRIPTION
**Pull request by maridematte**
# Description

[Features added, bugs fixed. Don't say "edited [some file].js, describe what you changed.]

# Reviewing

[Instructions on what parts of the code should be reviewed/tested.]

# Tests
I affirm that I've tested my code on:
- [x] Desktop
- [x] Tablet
- [x] Mobile
(Chrome tools counts)

### CODE REVIEW

**Comment by lkwatson** [comment]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Comment by lkwatson** [comment]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Comment by lkwatson** [comment]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Comment by lkwatson** [comment]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Comment by lkwatson** [comment]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Review by lkwatson — APPROVED** [review]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Comment by lkwatson** [comment]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Review by lkwatson — APPROVED** [review]
I got the following error upon switching to this branch:
```
./src/components/Footer/footer.js
Module not found: `/Users/watson/Desktop/Web Dev/beta/src/assets/SponsorLogos/Bose/BoseLogo.png` does not match the corresponding path on disk `boseLogo.png`.
```
Not sure what happened, but there were some unstaged changes to the Bose logo that I hadn't made.

Merge, but check that this doesn't pop up on the server when you do.

**Comment by maridematte** [comment]
One, what happened there?
Second, I removed one of the logos of bose, since the difference between them was capitalization, which might affect that?? idk

**Comment by maridematte** [comment]
One, what happened there?
Second, I removed one of the logos of bose, since the difference between them was capitalization, which might affect that?? idk

**Comment by lkwatson** [comment]
Welp.
It kept telling me it failed to post... so I kept trying.
https://status.github.com/messages

**Comment by maridematte** [comment]
That's weird. I'm gonna merge it and keep an eye on the site

**Pull request merged**
