### PR TITLE
Add input validation and grid styling to AttendBox+SponsorBox

### PR DESCRIPTION
**Pull request by warren**
# Description

This PR implements input validation for when a user tries to add themselves to our mailing list. It also adds grid styling to attend and sponsor boxes so they are aligned correctly.

# Reviewing

- Try adding an invalid email to the mailing list; it shouldn't let you.
- Try adding a valid email to the mailing list; it should let you.
- After loading the page make sure that attend and sponsor boxes are aligned on the right of the page.

# Tests
I affirm that I've tested my code on:
- [X] Desktop
- [X] Tablet
- [X] Mobile
(Chrome tools counts)

Screenshot:
bhacks wip homepage

### CODE REVIEW

**Review by maridematte — COMMENTED** [review]
Please merge master into branch, there are some conflicts because of it.

**Review by lkwatson — CHANGES_REQUESTED** [review]
How can I test the input validation?

I'm not positive, but from looking at the regex I believe emails like "example@sub.domain.com" will fail.

**Comment by lkwatson** [comment]
Bump @Warren-Partridge

**Comment by lkwatson** [comment]
Bump @Warren-Partridge

**Comment by warren** [comment]
Hey, sorry for the crazy late reply @lkwatson. I'm pretty sure the regex in this PR is working. I just tested "example@sub.domain.com" and it successfully validates. You can test yourself by checking out my branch, typing in the input field, and clicking the "Do it" button.

Let me know if it's not working on your end and I can investigate though.

**Comment by warren** [comment]
Yikes I messed up trying to rebase, I'm just going to close this PR and open another with my changes + master merge so it can go straight into master after review

**Pull request closed without merging**
