### PR TITLE
Make AttendAndSponsorBoxes responsive

### PR DESCRIPTION
**Pull request by warren**
# Description

This PR makes AttendAndSponsorBoxes look nice on screens other than just my macbook air

# Reviewing

View the website in a small, medium, and large screen and make sure the "Attend" and "Sponsor" sections look correct in all three.

# Tests
I affirm that I've tested my code on:
- [X] Desktop
- [X] Tablet
- [X] Mobile
(Chrome tools counts)

### CODE REVIEW

**Comment by lkwatson** [comment]
Much better. Hate to be nitpickey but...

screen shot 2018-07-31 at 9 24 55 pm

There's no grey border in the design.

Also, would be nice to keep "Subscribe" button inline for all sizes if possible.

**Review by lkwatson — CHANGES_REQUESTED** [review]
*Grey border on the button, to be clear

**Comment by lkwatson** [comment]
Also the shade of blue isn't the same as design v3.

**Comment by maridematte** [comment]
The mobile responsiveness is also not working. Please check the mock up on the drive for the mobile design

**Comment by warren** [comment]
Nah, nitpicking is good. I just pushed corrections to the colors and the button border.

To handle the inline button problem we will have to decrease the font size everywhere. Is there an agreed upon protocol for responsive font size?

**Comment by lkwatson** [comment]
> To handle the inline button problem we will have to decrease the font size everywhere. Is there an agreed upon protocol for responsive font size?

No but would be good to have one.
I'll approve, @maridematte?

**Review by lkwatson — APPROVED** [review]

**Comment by maridematte** [comment]
For the font size, as I already answered before, we're gonna keep it through and change the margins to adjust for the screen sizes. If we start to adjust too much, the fonts get too big on larger screens, as can be seen in one of Nam's commit where he tried to do responsive fonts.

I'm pretty sure you can adjust button sizes in another way that isn't just the size of the font, maybe include margins on the text inside the button.

If something looks off after the pr or after putting everything together I will fix it, since I'm going to go through the whole thing before putting it up.

**Review by maridematte — DISMISSED** [review]
The mobile responsiveness is still not working correctly

**Review by maridematte — APPROVED** [review]

**Comment by lkwatson** [comment]
In the future, can we squash and merge @maridematte to keep master clean?

**Pull request merged**
